// Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--rc2
// source: modules/auth/authPb/authPb.proto

package Golang_Project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structure
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{0}
}

type AccessTokenSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
}

func (x *AccessTokenSearchRequest) Reset() {
	*x = AccessTokenSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessTokenSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenSearchRequest) ProtoMessage() {}

func (x *AccessTokenSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenSearchRequest.ProtoReflect.Descriptor instead.
func (*AccessTokenSearchRequest) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTokenSearchRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AccessTokenSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
}

func (x *AccessTokenSearchResponse) Reset() {
	*x = AccessTokenSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_auth_authPb_authPb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessTokenSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenSearchResponse) ProtoMessage() {}

func (x *AccessTokenSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenSearchResponse.ProtoReflect.Descriptor instead.
func (*AccessTokenSearchResponse) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{2}
}

func (x *AccessTokenSearchResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type RolesCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RolesCountRequest) Reset() {
	*x = RolesCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_auth_authPb_authPb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountRequest) ProtoMessage() {}

func (x *RolesCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountRequest.ProtoReflect.Descriptor instead.
func (*RolesCountRequest) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{3}
}

type RolesCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RolesCountResponse) Reset() {
	*x = RolesCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_auth_authPb_authPb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountResponse) ProtoMessage() {}

func (x *RolesCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountResponse.ProtoReflect.Descriptor instead.
func (*RolesCountResponse) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{4}
}

func (x *RolesCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_modules_auth_authPb_authPb_proto protoreflect.FileDescriptor

var file_modules_auth_authPb_authPb_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x50, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x50, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3c, 0x0a, 0x18, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x35, 0x0a, 0x19, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x22, 0x13, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x32, 0x94, 0x01, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x68, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x19, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x12, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x61, 0x62, 0x70, 0x61, 0x72, 0x69, 0x6e,
	0x79, 0x61, 0x31, 0x31, 0x2f, 0x47, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_auth_authPb_authPb_proto_rawDescOnce sync.Once
	file_modules_auth_authPb_authPb_proto_rawDescData = file_modules_auth_authPb_authPb_proto_rawDesc
)

func file_modules_auth_authPb_authPb_proto_rawDescGZIP() []byte {
	file_modules_auth_authPb_authPb_proto_rawDescOnce.Do(func() {
		file_modules_auth_authPb_authPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_auth_authPb_authPb_proto_rawDescData)
	})
	return file_modules_auth_authPb_authPb_proto_rawDescData
}

var file_modules_auth_authPb_authPb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_auth_authPb_authPb_proto_goTypes = []interface{}{
	(*Empty)(nil),                     // 0: Empty
	(*AccessTokenSearchRequest)(nil),  // 1: AccessTokenSearchRequest
	(*AccessTokenSearchResponse)(nil), // 2: AccessTokenSearchResponse
	(*RolesCountRequest)(nil),         // 3: RolesCountRequest
	(*RolesCountResponse)(nil),        // 4: RolesCountResponse
}
var file_modules_auth_authPb_authPb_proto_depIdxs = []int32{
	1, // 0: AuthGrpcService.AccessTokenSearch:input_type -> AccessTokenSearchRequest
	3, // 1: AuthGrpcService.RolesCount:input_type -> RolesCountRequest
	2, // 2: AuthGrpcService.AccessTokenSearch:output_type -> AccessTokenSearchResponse
	4, // 3: AuthGrpcService.RolesCount:output_type -> RolesCountResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_auth_authPb_authPb_proto_init() }
func file_modules_auth_authPb_authPb_proto_init() {
	if File_modules_auth_authPb_authPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_auth_authPb_authPb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_auth_authPb_authPb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessTokenSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_auth_authPb_authPb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessTokenSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_auth_authPb_authPb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_auth_authPb_authPb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_auth_authPb_authPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_auth_authPb_authPb_proto_goTypes,
		DependencyIndexes: file_modules_auth_authPb_authPb_proto_depIdxs,
		MessageInfos:      file_modules_auth_authPb_authPb_proto_msgTypes,
	}.Build()
	File_modules_auth_authPb_authPb_proto = out.File
	file_modules_auth_authPb_authPb_proto_rawDesc = nil
	file_modules_auth_authPb_authPb_proto_goTypes = nil
	file_modules_auth_authPb_authPb_proto_depIdxs = nil
}
